apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagpdevelop-deployment
spec:
  selector:
    matchLabels:
      app: nagpdevelop-pod
  replicas: 4
  template:
    metadata:
      labels:
        app: nagpdevelop-pod
    spec:
      containers:
        - name: nagpdevelop-container
          image: agnanishelly/i-shellymehrotra-develop:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
    name: nagpdevelop-service
spec:
    ports:
    - name: http
      port: 80
      targetPort: 80
    selector:
        app: nagpdevelop-pod
    type: LoadBalancer

---

apiVersion: v1
kind: Secret
metadata:
  name: developsecret
type: Opaque
data:
  branch: c2VjcmV0IGZyb20gZGV2ZWxvcCBicmFuY2g=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: develop-configmap
data:
  branch: "secret from develop branch"