apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagpmaster-deployment
spec:
  selector:
    matchLabels:
      app: nagpmaster-pod
  replicas: 4
  template:
    metadata:
      labels:
        app: nagpmaster-pod
    spec:
      containers:
        - name: nagpmaster-container
          image: agnanishelly/i-shellymehrotra-master:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7005
--- 
apiVersion: v1
kind: Service
metadata:
    name: nagpmaster-service
spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80

    selector:
        app: nagpmaster-pod
    type: LoadBalancer

---

apiVersion: v1
kind: Secret
metadata:
  name: mastersecret
type: Opaque
data:
  branch: c2VjcmV0IG9mIGRldmVsb3AgYnJhbmNo

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: master-configmap
data:
  branch: "secret of master branch"